FROM python:3.11-slim-bookworm

WORKDIR /workspace

# -------------------------
# Install system dependencies
# -------------------------

RUN apt-get update && apt-get install -y \
    openjdk-17-jre-headless \
    curl \
    ca-certificates \
    procps \
    && rm -rf /var/lib/apt/lists/*

# -------------------------
# Spark local installation. Use if necessary
# Currently connecting to Spark Container on docker network
# -------------------------
#ENV SPARK_VERSION=3.5.1
#ENV HADOOP_VERSION=3
#
#RUN curl -fsSL https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz \
#    | tar -xz -C /opt/ \
#    && mv /opt/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} /opt/spark
#
#ENV SPARK_HOME=/opt/spark
#
#ENV PATH=$SPARK_HOME/bin:$JAVA_HOME/bin:$PATH
#RUN cp /opt/spark/conf/spark-env.sh.template /opt/spark/conf/spark-env.sh && \
#    echo "export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> /opt/spark/conf/spark-env.sh

# -------------------------
# Environment variables
# -------------------------
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

ENV PYSPARK_PYTHON=python
ENV PYSPARK_DRIVER_PYTHON=python

ENV PYTHONNOUSERSITE=1
ENV PYTHONPATH=/workspace

# -------------------------
# Python dependencies
# -------------------------
COPY requirements.txt /tmp/requirements.txt

RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -r /tmp/requirements.txt

CMD ["bash"]